const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const keys = require('./keys/keys');

const User = require('./models/User');

passport.serializeUser((user, done) => {
  done(null, user.id); // (err, identifier for follow up requests -> id is generated by MongoDB)
});

passport.deserializeUser((id, done) => {
  User.findById(id).then(user => {
    done(null, user);
  });
});

passport.use(
  new GoogleStrategy({
    clientID: keys.googleClientID,
    clientSecret: keys.googleClientSecret,
    callbackURL: '/auth/google/callback'
  },
  (accessToken, refreshToken, profile, done) => {
    User.signIn(profile, done);

    console.log('Access token: ' + accessToken);
    console.log('Refresh token: ' + refreshToken);
    console.log('Profile: ' + profile);
  })
);